### ISSUE TITLE
[BUG] : logic falis in few edge cases

### ISSUE THREAD

**Issue by amitanshusahu** [osbc2022/to-do-list#17]
### ✏️ Describe the bug

the code doesn't handel these edge cases 👇🏻 

### 📸 Screenshots

[screen-recorder-sun-oct-23-2022-17-14-30.webm](https://user-images.githubusercontent.com/83657737/197390328-651f9cc6-a941-40d9-8253-c96c4631079f.webm)
[screen-recorder-sun-oct-23-2022-17-16-03.webm](https://user-images.githubusercontent.com/83657737/197390333-bf1a7990-e710-49d6-8542-778840336935.webm)

**Comment by amitanshusahu** [comment]
i can work on this..

**Comment by osbc2022** [comment]
go for it :star_struck:
